### ISSUE TITLE
Specification

### ISSUE THREAD

**Issue by JhonnyJason** [libp2p/js-libp2p-peer-id#10]
Hallo LibP2P Team,
Love what you are doing and especially that you included the most awesome [Ed25519 codebase](https://github.com/paulmillr/noble-ed25519) for the peerIDs as default :-)

I have some Problem with a particular usecase and I could not find too much useful information about this in the [specs](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md). Also I have another uscase in mind I wanted to share with the team.

### Usecase: persisting the PeerId.
Many times we want to persist the PeerIds through new sessions. Then I would store the keys somewhere else to regenerate the PeerId on the next start.

I think it is suboptimal that all "toString" methods are overwritten, so that only the multihash is provided.
How would/should one export the PeerId Object with all the keys to be parsed again?

I could manually pick out the type and privateKey to store it in JSON somewhere, then use the "peer-id-factory" to call createFromJSON (which is IMHO suboptimally named, because JSON from my perspective entails that it is a JSON string - createFromJSON requires an object)

### Usecase: generate "contextual" PeerId

Sometimes I want to generate a peerId which is only recognized within a certain context.
For Example you have sub-graphs of peers who know eachother, they share the same context and could identify eachother - outsiders could not.

One Idea: contextedPeerId = hash( publicKey + context )
The context could be like (an accurate timestamp + shared secret string) - valid for one message.
Or the context could be like (rounded timestamp + shared secret string) - valid for a certain timespan.

This way only nodes who know the publicKey +  context could identify the peerId and securely communicate.
This could be a bigger issue for the protocol in general.

### Maybe both usecases need an additional level with new keys from inside the App.

Maybe the best solution is to use the PeerId purely for libP2P connections - so then they should be kept ephemeral - recreated on any connection break, better also be switched after some time.
Then the level within the Application could use their Keys and corresponding Ids on Top of it. Which seems simple enough for a basic solution, but does seem very redundant. Like anonymity on Level 3 is easily beat by troubles on Level 1 and 2.

**Comment by mpetrunic** [comment]
You can use https://github.com/libp2p/js-libp2p-peer-id/blob/master/packages/libp2p-peer-id/src/index.ts#L235 to create PeerId from keys you stored somehow.

If you want some compact format, use https://github.com/libp2p/js-libp2p-peer-id/blob/master/packages/libp2p-peer-id-factory/src/index.ts#L49 to export to protobuf and https://github.com/libp2p/js-libp2p-peer-id/blob/master/packages/libp2p-peer-id-factory/src/index.ts#L57 to restore it back
